### ISSUE TITLE
Migration `migrate_reports_tables` fails due to incorrect datetime value

### ISSUE THREAD

**Issue by superextinct** [barrelstrength/craft-sprout-data-studio#2]
### Description

Hi, thanks for your work in making Data Studio available to Craft 4! I've encountered an issue while installing the plugin (or rather upgrading from a previous version):

```Installing plugin "sprout-data-studio" ... error: An error occurred while executing the "BarrelStrength\Sprout\datastudio\migrations\m211101_000008_migrate_reports_tables migration: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '2023-02-28T22:17:34+01:00' for column `db`.`content`.`dateCreated` at row 1
The SQL being executed was: INSERT INTO `content` (`elementId`, `siteId`, `dateCreated`, `dateUpdated`, `uid`) VALUES (185850, 2, '2023-02-28T22:17:34+01:00', '2023-02-28T22:17:34+01:00', '08cdb8bd-9101-4c4f-9924-8dab79cd89d3')```

### How to reproduce

Have some rows in the retired `sproutreports_datasources` table:

```INSERT INTO `sproutreports_datasources` (`id`, `viewContext`, `type`, `allowNew`, `dateCreated`, `dateUpdated`, `uid`) VALUES
(1, 'sprout-reports', 'barrelstrength\\sproutbasereports\\datasources\\CustomQuery', 1, '2021-11-24 11:06:55', '2021-11-24 11:06:55', '55b6cdc6-dd4b-4a97-8a79-ae8cf5d450b2'),
(2, 'sprout-reports', 'barrelstrength\\sproutbasereports\\datasources\\CustomTwigTemplate', 1, '2021-11-24 11:06:55', '2021-11-24 11:06:55', '356a66d8-f0c3-4756-af42-62a3cb414704'),
(3, 'sprout-reports', 'barrelstrength\\sproutbasereports\\datasources\\Users', 1, '2021-11-24 11:06:55', '2021-11-24 11:06:55', '9e96da6e-f86e-4d28-a26e-0371e345e404');```

Install the plugin and let the migrations run.

This issue might not be reproducible for environments that do not have [`STRICT_TRANS_TABLES`](https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_strict_trans_tables) enabled. I'm encoutering this while using DDEV and having a PHP default timezone set to `Europe/Berlin`.

### Sprout Version

4.44.444

### Craft Version

4.3.10

### Database Type Version

MySQL 10.3.37

**Comment by BenParizek** [comment]
Thanks @superextinct - for the report and the PR.

I expect you may have things sorted at this point but this updated will be included for new installs.
